import Head from 'next/head';
import Image from 'next/image';
import About from '../components/About';
import Banner from '../components/Banner';
import Banner1 from '../components/Banner1';
import Hero1 from '../components/Hero1';
import NavBar from '../components/Nav';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hitex Diagnostic</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* lwangasamson10@gmail.com */}

      <main className={styles.main}>
        <Banner />
        <NavBar />
        <Hero1 />
        <Banner1 />
        <About />
      </main>
    </div>
  );
}
