import Image from 'next/image';
import Mini from '../components/Mini';

const Total = () => {
  return (
    <div>
      <Mini
        head={'Waste Management & Supply Of Incinerators'}
        sub="Waste management & supply of incinerators"
      />
      <div style={{ padding: '8rem 2rem' }}>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
            // gridAutoRows: '450px',
            gap: '2rem',
          }}
        >
          <div style={{ position: 'relative' }}>
            <Image
              src={'/assets/image.png'}
              alt="bio"
              layout="fill"
              objectFit="cover"
            />
          </div>
          <div style={{ marginBottom: '1rem' }}>
            <p style={{ lineHeight: '2rem' }}>
              There are enormous biosafety and biosecurity risks resulting from
              poor Healthcare waste Management (HCWM) across healthcare
              facilities and the final disposal sites. The situation has further
              been exacerbated by the lack of well-designed systems and final
              disposal infrastructure to handle the ever-increasing waste
              management requirements. Critical to this is the rapid advancement
              in technology resulting in the development and employment of novel
              point-of-care testing (POCT) technologies both at static and
              outreach sites, generation of liquid waste from laboratory
              procedures with some of this waste presenting carcinogenic
              elements upon consumption. As the advancement in technology is
              happening rapidly compared to the mitigation measures, at Hitex we
              believe there is need work with our customers to map out their
              work routines and proactively design systems that would enable
              safe and secure disposal of the various waste streams generated by
              the facility. Our team has worked with the Uganda ministry of
              health department of National health laboratory and diagnostic
              services to develop: The national policy and guidelines on waste
              management, assessment tool for HCWM, and the waste management
              training curriculum. We also supply incinerators and provide after
              installation services to our customers based on their need
            </p>
          </div>
        </div>
        <div style={{ display: 'flex', gap: '20px', paddingBlock: '50px' }}>
          <Image src={'/assets/p.jpg'} alt="bio" width="500px" height="400px" />
          <Image
            src={'/assets/lo.jpg'}
            alt="bio"
            width="500px"
            height="400px"
          />
        </div>
      </div>
      <br />
    </div>
  );
};

export default Total;
