import Image from 'next/image';

const Total = () => {
  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'center',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '0 2rem',
        lineHeight: '40px',
        backgroundColor: 'whitesmoke',
      }}
    >
      <div>
        <h2
          style={{
            marginTop: '5rem',
            marginBottom: '2rem',
            textAlign: 'center',
            // backgroundColor: 'rgb(28, 28, 143)',
            padding: '2.5rem 0',
            color: 'rgb(28, 28, 143)',
          }}
        >
          Waste management & supply of incinerators
        </h2>
        <Image src={'/assets/was.jpg'} alt="bio" width="1000px" height="400px" />
      </div>
      <div>
        <p>
          There are enormous biosafety and biosecurity risks resulting from poor
          Healthcare waste Management (HCWM) across healthcare facilities and
          the final disposal sites. The situation has further been exacerbated
          by the lack of well-designed systems and final disposal infrastructure
          to handle the ever-increasing waste management requirements. Critical
          to this is the rapid advancement in technology resulting in the
          development and employment of novel point-of-care testing (POCT)
          technologies both at static and outreach sites, generation of liquid
          waste from laboratory procedures with some of this waste presenting
          carcinogenic elements upon consumption. As the advancement in
          technology is happening rapidly compared to the mitigation measures,
          at Hitex we believe there is need work with our customers to map out
          their work routines and proactively design systems that would enable
          safe and secure disposal of the various waste streams generated by the
          facility. Our team has worked with the Uganda ministry of health
          department of National health laboratory and diagnostic services to
          develop: The national policy and guidelines on waste management,
          assessment tool for HCWM, and the waste management training
          curriculum. We also supply incinerators and provide after installation
          services to our customers based on their need
        </p>
      </div>
      <div style={{ display: 'flex', gap: '20px', paddingBlock: '50px'}}>
      <Image src={'/assets/p.jpg'} alt="bio" width="500px" height="400px" />
      <Image src={'/assets/lo.jpg'} alt="bio" width="500px" height="400px" />
      </div>
    </div>
  );
};

export default Total;
